const products = [
    {
        "id": 1,
        "name":"Alcohol Pad",
        "price": 729,
        "image": "img/covid19/alcoholpad.webp",
        "description": "Alcohol pads are essential for disinfecting surfaces and medical equipment.",
    },
    {
        "id": 2,
        "name":"Rossmax",
        "price": 2000,
        "image": "img/covid19/rossmax.webp",
        "description": "Rossmax provides accurate and reliable medical devices for home and professional use.",
    },
    {
        "id": 3,
        "name":"Face Shield",
        "price": 50,
        "image": "img/covid19/facesheild.webp",
        "description": "Face shields offer protection against airborne particles and fluids.",
    },
    {
        "id": 4,
        "name":"Nebulizer",
        "price": 85,
        "image": "img/covid19/nebulizer.webp",
        "description": "Nebulizers deliver medication in mist form for respiratory treatment.",
    },
    {
        "id": 5,
        "name":"Product 1",
        "price": 729,
        "image": "img/womencare/1.webp",
        "description": "Description for Product 1",
    },
    {
        "id": 6,
        "name":"Product 2",
        "price": 1200,
        "image": "img/womencare/2.webp",
        "description": "Description for Product 2",
    },
    {
        "id": 7,
        "name":"Product 3",
        "price": 800,
        "image": "img/womencare/3.webp",
        "description": "Description for Product 3",
    },
    {
        "id": 8,
        "name":"Product 4",
        "price": 22,
        "image": "img/womencare/4.webp",
        "description": "Description for Product 4",
    },
    {
        "id": 9,
        "name":"Product 5",
        "price": 90,
        "image": "img/devices/1.webp",
        "description": "Description for Product 5",
    },
    {
        "id": 10,
        "name":"Product 6",
        "price": 2800,
        "image": "img/devices/2.webp",
        "description": "Description for Product 6",
    },
    {
        "id": 11,
        "name":"Product 7",
        "price": 1440,
        "image": "img/devices/3.webp",
        "description": "Description for Product 7",
    },
    {
        "id": 12,
        "name":"Product 8",
        "price": 3000,
        "image": "img/devices/4.webp",
        "description": "Description for Product 8",
    },
    {
        "id": 13,
        "name":"Product 9",
        "price": 7,
        "image": "img/nutrition/5.webp",
        "description": "Description for Product 9",
    },
    {
        "id": 14,
        "name":"Product 10",
        "price": 710,
        "image": "img/nutrition/6.webp",
        "description": "Description for Product 10",
    },
    {
        "id": 15,
        "name":"Product 11",
        "price": 14,
        "image": "img/nutrition/3.webp",
        "description": "Description for Product 11",
    },
    {
        "id": 16,
        "name":"Product 12",
        "price": 4,
        "image": "img/nutrition/4.webp",
        "description": "Description for Product 12",
    }
];

export default products;
